### PR TITLE
Removing Fody and Janitor.Fody

### PR DESCRIPTION
**Pull request by rominator1983**
Removing dependency on Fody and Janitor.Fody by implementing Disposable pattern ourselves.

### CODE REVIEW

**Review by GeorgDangl — DISMISSED** [review]

**Comment by stesee** [comment]
The files do not match the expectation... I updated the tests and added some githubactions things to get the expectation and the actual files into the test run outcome... please review why the test break @rominator1983

**Comment by stesee** [comment]
The failing tests are not caused by your changes. Seems like github changed some things on their runners. That need to be addressed before merging to main.

**Comment by stesee** [comment]
could be releated to https://github.com/mono/SkiaSharp/issues/752

**Comment by rominator1983** [comment]
I'll look into that and probably do another PR to address that. Thanks for your analysis.

**Comment by stesee** [comment]
https://github.com/stesee/ClosedXML/pull/33 should fix the issues

**Review by stesee — APPROVED** [review]

**Pull request merged**
